name: Generate pacman animation

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"

  workflow_dispatch:

  push:
    branches:
    - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}


      - name: Push generated files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          cp dist/pacman-contribution-graph.svg ./pacman-contribution-graph.svg
          git add pacman-contribution-graph.svg
          git commit -m "Update pacman contribution graph" --allow-empty
          git push